// <auto-generated />
namespace CA3_RentalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Haventaclue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Haventaclue));
        
        string IMigrationMetadata.Id
        {
            get { return "202405241547129_Haventaclue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
